window.__A2UI_DATA__ = {
  "state": {
    "activeTab": "tab1",
    "userKeyword": "",
    "roleKeyword": "",
    "policyKeyword": "",
    "userTableList": [
      { "id": "USR-1001", "userName": "张启明", "account": "zhangqm", "department": "数据平台部", "roleName": "平台管理员", "statusText": "正常", "statusColor": "success", "lastLoginTime": "2026-09-12 09:24", "nextActionText": "查看关联角色" },
      { "id": "USR-1002", "userName": "李思远", "account": "lisy", "department": "数据分析部", "roleName": "数据分析师", "statusText": "正常", "statusColor": "success", "lastLoginTime": "2026-09-12 08:51", "nextActionText": "查看关联角色" },
      { "id": "USR-1003", "userName": "王雪", "account": "wangxue", "department": "运营中心", "roleName": "运营专员", "statusText": "正常", "statusColor": "success", "lastLoginTime": "2026-09-11 19:07", "nextActionText": "查看关联角色" },
      { "id": "USR-1004", "userName": "陈牧", "account": "chenmu", "department": "安全合规部", "roleName": "审计员", "statusText": "待激活", "statusColor": "warning", "lastLoginTime": "2026-09-08 10:12", "nextActionText": "查看关联角色" },
      { "id": "USR-1005", "userName": "赵芸", "account": "zhaoyun", "department": "数据平台部", "roleName": "开发工程师", "statusText": "正常", "statusColor": "success", "lastLoginTime": "2026-09-11 17:45", "nextActionText": "查看关联角色" },
      { "id": "USR-1006", "userName": "周皓", "account": "zhouhao", "department": "运维保障部", "roleName": "系统运维", "statusText": "已停用", "statusColor": "error", "lastLoginTime": "2026-08-29 11:32", "nextActionText": "查看关联角色" },
      { "id": "USR-1007", "userName": "吴桐", "account": "wutong", "department": "数据分析部", "roleName": "数据分析师", "statusText": "正常", "statusColor": "success", "lastLoginTime": "2026-09-12 09:02", "nextActionText": "查看关联角色" },
      { "id": "USR-1008", "userName": "郑清", "account": "zhengqing", "department": "产品管理部", "roleName": "访客", "statusText": "待激活", "statusColor": "warning", "lastLoginTime": "2026-09-05 15:18", "nextActionText": "查看关联角色" },
      { "id": "USR-1009", "userName": "孙越", "account": "sunyue", "department": "运维保障部", "roleName": "系统运维", "statusText": "正常", "statusColor": "success", "lastLoginTime": "2026-09-12 07:58", "nextActionText": "查看关联角色" },
      { "id": "USR-1010", "userName": "何静", "account": "hejing", "department": "安全合规部", "roleName": "审计员", "statusText": "已停用", "statusColor": "error", "lastLoginTime": "2026-08-21 14:06", "nextActionText": "查看关联角色" }
    ],
    "roleTableList": [
      { "id": "ROLE-01", "roleName": "平台管理员", "roleCode": "platform_admin", "userCount": 12, "dataScope": "全量数据", "statusText": "启用", "statusColor": "success", "updatedAt": "2026-09-10 16:30", "nextActionText": "查看权限策略" },
      { "id": "ROLE-02", "roleName": "数据分析师", "roleCode": "analyst", "userCount": 48, "dataScope": "本部门数据", "statusText": "启用", "statusColor": "success", "updatedAt": "2026-09-09 10:14", "nextActionText": "查看权限策略" },
      { "id": "ROLE-03", "roleName": "运营专员", "roleCode": "operator", "userCount": 63, "dataScope": "本部门及下级", "statusText": "启用", "statusColor": "success", "updatedAt": "2026-09-08 18:22", "nextActionText": "查看权限策略" },
      { "id": "ROLE-04", "roleName": "审计员", "roleCode": "auditor", "userCount": 8, "dataScope": "全量数据（只读）", "statusText": "启用", "statusColor": "success", "updatedAt": "2026-09-05 09:40", "nextActionText": "查看权限策略" },
      { "id": "ROLE-05", "roleName": "开发工程师", "roleCode": "developer", "userCount": 35, "dataScope": "项目数据", "statusText": "启用", "statusColor": "success", "updatedAt": "2026-09-04 15:07", "nextActionText": "查看权限策略" },
      { "id": "ROLE-06", "roleName": "系统运维", "roleCode": "sysops", "userCount": 9, "dataScope": "全量数据", "statusText": "启用", "statusColor": "success", "updatedAt": "2026-09-03 11:26", "nextActionText": "查看权限策略" },
      { "id": "ROLE-07", "roleName": "访客", "roleCode": "guest", "userCount": 126, "dataScope": "公开数据", "statusText": "停用", "statusColor": "error", "updatedAt": "2026-08-30 14:55", "nextActionText": "查看权限策略" },
      { "id": "ROLE-08", "roleName": "数据治理专员", "roleCode": "data_steward", "userCount": 15, "dataScope": "本部门数据", "statusText": "启用", "statusColor": "success", "updatedAt": "2026-08-28 17:12", "nextActionText": "查看权限策略" },
      { "id": "ROLE-09", "roleName": "外部协作方", "roleCode": "external_partner", "userCount": 22, "dataScope": "指定数据集", "statusText": "待审核", "statusColor": "warning", "updatedAt": "2026-08-26 10:48", "nextActionText": "查看权限策略" },
      { "id": "ROLE-10", "roleName": "临时支持", "roleCode": "temp_support", "userCount": 4, "dataScope": "指定数据集", "statusText": "停用", "statusColor": "error", "updatedAt": "2026-08-22 16:33", "nextActionText": "查看权限策略" }
    ],
    "policyTableList": [
      { "id": "POL-2001", "policyName": "用户信息读写策略", "policyType": "数据访问", "scopeText": "用户信息表", "riskText": "中风险", "riskColor": "warning", "updatedAt": "2026-09-11 14:05", "nextActionText": "返回用户信息" },
      { "id": "POL-2002", "policyName": "角色授权变更策略", "policyType": "权限管理", "scopeText": "角色管理表", "riskText": "高风险", "riskColor": "error", "updatedAt": "2026-09-11 11:42", "nextActionText": "返回用户信息" },
      { "id": "POL-2003", "policyName": "敏感字段脱敏策略", "policyType": "数据脱敏", "scopeText": "手机号 / 证件号", "riskText": "高风险", "riskColor": "error", "updatedAt": "2026-09-10 09:18", "nextActionText": "返回用户信息" },
      { "id": "POL-2004", "policyName": "登录行为审计策略", "policyType": "安全审计", "scopeText": "全量登录日志", "riskText": "中风险", "riskColor": "warning", "updatedAt": "2026-09-09 16:27", "nextActionText": "返回用户信息" },
      { "id": "POL-2005", "policyName": "数据导出审批策略", "policyType": "流程管控", "scopeText": "导出任务", "riskText": "中风险", "riskColor": "warning", "updatedAt": "2026-09-08 13:50", "nextActionText": "返回用户信息" },
      { "id": "POL-2006", "policyName": "接口访问限流策略", "policyType": "接口安全", "scopeText": "开放 API", "riskText": "低风险", "riskColor": "default", "updatedAt": "2026-09-07 10:11", "nextActionText": "返回用户信息" },
      { "id": "POL-2007", "policyName": "离职账号回收策略", "policyType": "账号治理", "scopeText": "用户信息表", "riskText": "中风险", "riskColor": "warning", "updatedAt": "2026-09-05 15:36", "nextActionText": "返回用户信息" },
      { "id": "POL-2008", "policyName": "权限定期复核策略", "policyType": "权限治理", "scopeText": "角色管理表", "riskText": "低风险", "riskColor": "default", "updatedAt": "2026-09-04 09:58", "nextActionText": "返回用户信息" },
      { "id": "POL-2009", "policyName": "跨部门数据共享策略", "policyType": "数据共享", "scopeText": "项目数据集", "riskText": "高风险", "riskColor": "error", "updatedAt": "2026-09-02 17:21", "nextActionText": "返回用户信息" },
      { "id": "POL-2010", "policyName": "访客只读策略", "policyType": "数据访问", "scopeText": "公开数据集", "riskText": "低风险", "riskColor": "default", "updatedAt": "2026-09-01 11:04", "nextActionText": "返回用户信息" }
    ]
  },
  "rootId": "pageDataCenterRoot",
  "elements": [
    { "id": "pageDataCenterRoot", "component": "div", "props": { "className": "flex flex-col min-h-screen bg-surface-container-lowest p-page gap-section" }, "children": ["headerPageBar", "mainContentCard"] },

    { "id": "headerPageBar", "component": "header", "props": { "className": "flex flex-col gap-2" }, "children": ["headerPageBreadcrumb", "headerPageTitleRow"] },
    { "id": "headerPageBreadcrumb", "component": "Breadcrumb", "props": { "items": [{ "title": "数据治理中心" }, { "title": "数据表单" }] } },
    { "id": "headerPageTitleRow", "component": "div", "props": { "className": "flex items-start justify-between gap-4" }, "children": ["headerPageTitleGroup", "headerPageActions"] },
    { "id": "headerPageTitleGroup", "component": "div", "props": { "className": "flex flex-col gap-1" }, "children": ["headerPageTitle", "headerPageSubtitle"] },
    { "id": "headerPageTitle", "component": "h1", "props": { "className": "text-3xl font-bold text-on-surface", "value": "数据表单中心" } },
    { "id": "headerPageSubtitle", "component": "p", "props": { "className": "text-md text-on-surface-variant", "value": "在页签内查看业务数据表，点击表格中的跳转链接可直接切换到关联页签。" } },
    { "id": "headerPageActions", "component": "div", "props": { "className": "flex items-center gap-2" }, "children": ["headerPageExportBtn", "headerPageCreateBtn"] },
    { "id": "headerPageExportBtn", "component": "Button", "props": { "value": "导出数据", "color": "default", "icon": "download", "iconPlacement": "start" } },
    { "id": "headerPageCreateBtn", "component": "Button", "props": { "value": "新建记录", "color": "primary", "icon": "plus", "iconPlacement": "start" } },

    { "id": "mainContentCard", "component": "div", "props": { "className": "bg-surface-container-highest rounded-container shadow-card p-inset" }, "children": ["mainTabsData"] },
    { "id": "mainTabsData", "component": "Tabs", "props": { "activeKey": { "path": "/activeTab" }, "types": "line", "size": "medium" }, "children": ["tabItemUser", "tabItemRole", "tabItemPolicy"] },

    { "id": "tabItemUser", "component": "TabItem", "props": { "key": "tab1", "label": "用户信息", "icon": "users", "content": { "componentId": "panelUser" } } },
    { "id": "panelUser", "component": "div", "props": { "className": "flex flex-col gap-4" }, "children": ["panelUserToolbar", "panelUserTable"] },
    { "id": "panelUserToolbar", "component": "div", "props": { "className": "flex items-center justify-between gap-3" }, "children": ["panelUserSearchInput", "panelUserToolbarRight"] },
    { "id": "panelUserSearchInput", "component": "Input", "props": { "value": { "path": "/userKeyword" }, "placeholder": "搜索用户名、账号或部门", "prefix": "search", "size": "medium", "className": "w-80" } },
    { "id": "panelUserToolbarRight", "component": "div", "props": { "className": "flex items-center gap-3" }, "children": ["panelUserSummary", "panelUserFilterBtn"] },
    { "id": "panelUserSummary", "component": "span", "props": { "className": "text-sm text-on-surface-variant", "value": "共 10 条记录" } },
    { "id": "panelUserFilterBtn", "component": "Button", "props": { "value": "筛选", "color": "default", "icon": "list-filter", "iconPlacement": "start" } },
    { "id": "panelUserTable", "component": "Table", "props": { "rowKey": "id", "size": "medium", "dataSource": { "path": "/userTableList" }, "columns": [{ "title": "用户名", "dataIndex": "userName", "minWidth": 160 }, { "title": "账号", "dataIndex": "account" }, { "title": "所属部门", "dataIndex": "department" }, { "title": "角色", "dataIndex": "roleName" }, { "title": "状态", "dataIndex": "statusText", "align": "center", "width": 110 }, { "title": "最近登录", "dataIndex": "lastLoginTime" }, { "title": "快捷跳转", "dataIndex": "nextActionText", "width": 190, "fixed": "end" }] }, "children": { "path": "/userTableList", "componentId": "userRowTemplate" } },
    { "id": "userRowTemplate", "component": "TableRow", "children": ["userNameCell", "userAccountCell", "userDepartmentCell", "userRoleCell", "userStatusCell", "userLastLoginCell", "userActionCell"] },
    { "id": "userNameCell", "component": "span", "props": { "value": { "path": "userName" } } },
    { "id": "userAccountCell", "component": "span", "props": { "value": { "path": "account" } } },
    { "id": "userDepartmentCell", "component": "span", "props": { "value": { "path": "department" } } },
    { "id": "userRoleCell", "component": "Tag", "props": { "value": { "path": "roleName" }, "variant": "outlined" } },
    { "id": "userStatusCell", "component": "Tag", "props": { "value": { "path": "statusText" }, "color": { "path": "statusColor" } } },
    { "id": "userLastLoginCell", "component": "span", "props": { "value": { "path": "lastLoginTime" } } },
    { "id": "userActionCell", "component": "Button", "props": { "value": { "path": "nextActionText" }, "types": "link", "icon": "arrow-right", "iconPlacement": "end", "onClick": { "action": "setState", "args": { "path": "/activeTab", "value": "tab2" } } } },

    { "id": "tabItemRole", "component": "TabItem", "props": { "key": "tab2", "label": "角色管理", "icon": "user-cog", "content": { "componentId": "panelRole" } } },
    { "id": "panelRole", "component": "div", "props": { "className": "flex flex-col gap-4" }, "children": ["panelRoleToolbar", "panelRoleTable"] },
    { "id": "panelRoleToolbar", "component": "div", "props": { "className": "flex items-center justify-between gap-3" }, "children": ["panelRoleSearchInput", "panelRoleToolbarRight"] },
    { "id": "panelRoleSearchInput", "component": "Input", "props": { "value": { "path": "/roleKeyword" }, "placeholder": "搜索角色名称或角色标识", "prefix": "search", "size": "medium", "className": "w-80" } },
    { "id": "panelRoleToolbarRight", "component": "div", "props": { "className": "flex items-center gap-3" }, "children": ["panelRoleSummary", "panelRoleFilterBtn"] },
    { "id": "panelRoleSummary", "component": "span", "props": { "className": "text-sm text-on-surface-variant", "value": "共 10 条记录" } },
    { "id": "panelRoleFilterBtn", "component": "Button", "props": { "value": "筛选", "color": "default", "icon": "list-filter", "iconPlacement": "start" } },
    { "id": "panelRoleTable", "component": "Table", "props": { "rowKey": "id", "size": "medium", "dataSource": { "path": "/roleTableList" }, "columns": [{ "title": "角色名称", "dataIndex": "roleName", "minWidth": 160 }, { "title": "角色标识", "dataIndex": "roleCode" }, { "title": "关联用户数", "dataIndex": "userCount", "align": "right", "width": 130 }, { "title": "数据范围", "dataIndex": "dataScope" }, { "title": "状态", "dataIndex": "statusText", "align": "center", "width": 110 }, { "title": "更新时间", "dataIndex": "updatedAt" }, { "title": "快捷跳转", "dataIndex": "nextActionText", "width": 190, "fixed": "end" }] }, "children": { "path": "/roleTableList", "componentId": "roleRowTemplate" } },
    { "id": "roleRowTemplate", "component": "TableRow", "children": ["roleNameCell", "roleCodeCell", "roleUserCountCell", "roleDataScopeCell", "roleStatusCell", "roleUpdatedAtCell", "roleActionCell"] },
    { "id": "roleNameCell", "component": "span", "props": { "value": { "path": "roleName" } } },
    { "id": "roleCodeCell", "component": "span", "props": { "value": { "path": "roleCode" } } },
    { "id": "roleUserCountCell", "component": "span", "props": { "value": { "path": "userCount" } } },
    { "id": "roleDataScopeCell", "component": "Tag", "props": { "value": { "path": "dataScope" }, "variant": "outlined" } },
    { "id": "roleStatusCell", "component": "Tag", "props": { "value": { "path": "statusText" }, "color": { "path": "statusColor" } } },
    { "id": "roleUpdatedAtCell", "component": "span", "props": { "value": { "path": "updatedAt" } } },
    { "id": "roleActionCell", "component": "Button", "props": { "value": { "path": "nextActionText" }, "types": "link", "icon": "arrow-right", "iconPlacement": "end", "onClick": { "action": "setState", "args": { "path": "/activeTab", "value": "tab3" } } } },

    { "id": "tabItemPolicy", "component": "TabItem", "props": { "key": "tab3", "label": "权限策略", "icon": "key-round", "content": { "componentId": "panelPolicy" } } },
    { "id": "panelPolicy", "component": "div", "props": { "className": "flex flex-col gap-4" }, "children": ["panelPolicyToolbar", "panelPolicyTable"] },
    { "id": "panelPolicyToolbar", "component": "div", "props": { "className": "flex items-center justify-between gap-3" }, "children": ["panelPolicySearchInput", "panelPolicyToolbarRight"] },
    { "id": "panelPolicySearchInput", "component": "Input", "props": { "value": { "path": "/policyKeyword" }, "placeholder": "搜索策略名称或策略类型", "prefix": "search", "size": "medium", "className": "w-80" } },
    { "id": "panelPolicyToolbarRight", "component": "div", "props": { "className": "flex items-center gap-3" }, "children": ["panelPolicySummary", "panelPolicyFilterBtn"] },
    { "id": "panelPolicySummary", "component": "span", "props": { "className": "text-sm text-on-surface-variant", "value": "共 10 条记录" } },
    { "id": "panelPolicyFilterBtn", "component": "Button", "props": { "value": "筛选", "color": "default", "icon": "list-filter", "iconPlacement": "start" } },
    { "id": "panelPolicyTable", "component": "Table", "props": { "rowKey": "id", "size": "medium", "dataSource": { "path": "/policyTableList" }, "columns": [{ "title": "策略名称", "dataIndex": "policyName", "minWidth": 180 }, { "title": "策略类型", "dataIndex": "policyType" }, { "title": "生效范围", "dataIndex": "scopeText" }, { "title": "风险等级", "dataIndex": "riskText", "align": "center", "width": 110 }, { "title": "更新时间", "dataIndex": "updatedAt" }, { "title": "快捷跳转", "dataIndex": "nextActionText", "width": 190, "fixed": "end" }] }, "children": { "path": "/policyTableList", "componentId": "policyRowTemplate" } },
    { "id": "policyRowTemplate", "component": "TableRow", "children": ["policyNameCell", "policyTypeCell", "policyScopeCell", "policyRiskCell", "policyUpdatedAtCell", "policyActionCell"] },
    { "id": "policyNameCell", "component": "span", "props": { "value": { "path": "policyName" } } },
    { "id": "policyTypeCell", "component": "Tag", "props": { "value": { "path": "policyType" }, "variant": "outlined" } },
    { "id": "policyScopeCell", "component": "span", "props": { "value": { "path": "scopeText" } } },
    { "id": "policyRiskCell", "component": "Tag", "props": { "value": { "path": "riskText" }, "color": { "path": "riskColor" } } },
    { "id": "policyUpdatedAtCell", "component": "span", "props": { "value": { "path": "updatedAt" } } },
    { "id": "policyActionCell", "component": "Button", "props": { "value": { "path": "nextActionText" }, "types": "link", "icon": "arrow-right", "iconPlacement": "end", "onClick": { "action": "setState", "args": { "path": "/activeTab", "value": "tab1" } } } }
  ]
};