import type { Config } from 'tailwindcss'

export default {
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
    './src/jsonStorage/*.json',
    '../test-project/test/**/*.json'
  ],
  theme: {
    "extend": {
      "colors": {
        "primary": "var(--primary, #0067D1)",
        "on-primary": "var(--on-primary, #FFFFFF)",
        "primary-container": "var(--primary-container, #E6F2FD)",
        "on-primary-container": "var(--on-primary-container, #191919)",
        "primary-fixed": "var(--primary-fixed, #0067D1)",
        "primary-fixed-dim": "var(--primary-fixed-dim, #004EA8)",
        "on-primary-fixed": "var(--on-primary-fixed, #FFFFFF)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant, #F3F3F3)", 
        
        "surface": "var(--surface, #F3F3F3)",
        "surface-dim": "var(--surface-dim, #DFDFDF)",
        "surface-bright": "var(--surface-bright, #FFFFFF)",
        "on-surface": "var(--on-surface, #191919)",
        "surface-variant": "var(--surface-variant, rgba(192,192,192,0.2))",
        "on-surface-variant": "var(--on-surface-variant, #777777)",
        "surface-container-lowest": "var(--surface-container-lowest, #F3F3F3)",
        "surface-container-low": "var(--surface-container-low, rgba(255,255,255,0.5))",
        "surface-container": "var(--surface-container, rgba(255,255,255,0.65))",
        "surface-container-high": "var(--surface-container-high, rgba(255,255,255,0.8))",
        "surface-container-highest": "var(--surface-container-highest, #FFFFFF)",
        
        "inverse-surface": "var(--inverse-surface, #191919)",
        "inverse-on-surface": "var(--inverse-on-surface, #FFFFFF)",
        "inverse-on-surface-variant": "var(--inverse-on-surface-variant, #C9C9C9)",
        "inverse-primary": "var(--inverse-primary, #0067D1)",

        "error": "var(--error, #E02128)",
        "on-error": "var(--on-error, #FFFFFF)",
        "error-container": "var(--error-container, #FEE7E8)",
        "on-error-container": "var(--on-error-container, #191919)",
        
        "success": "var(--success, #09AA71)",
        "on-success": "var(--on-success, #FFFFFF)",
        "success-container": "var(--success-container, #E7FBF2)",
        "on-success-container": "var(--on-success-container, #191919)",

        "critical": "var(--critical, #F4840C)",
        "on-critical": "var(--on-critical, #FFFFFF)",
        "critical-container": "var(--critical-container, #FEF5E8)",
        "on-critical-container": "var(--on-critical-container, #191919)",

        "warning": "var(--warning, #FCC800)",
        "on-warning": "var(--on-warning, #FFFFFF)",
        "warning-container": "var(--warning-container, #FEFCE0)",
        "on-warning-container": "var(--on-warning-container, #191919)",

        "info": "var(--info, #0067D1)",
        "on-info": "var(--on-info, #FFFFFF)",
        "info-container": "var(--info-container, #E6F2FD)",
        "on-info-container": "var(--on-info-container, #191919)",

        "divider": "var(--divider, #F3F3F3)",

        /* ==========================================================================
           基础色阶 (Primitive Colors) — from base.css
           Usage: text-base-neutral-50, bg-base-primary-500, border-base-error-200
           ========================================================================== */
        "base": {
          "neutral": {
            "0": "var(--neutral-0, #FFFFFF)",
            "50": "var(--neutral-50, #F3F3F3)",
            "100": "var(--neutral-100, #DFDFDF)",
            "200": "var(--neutral-200, #C9C9C9)",
            "300": "var(--neutral-300, #AEAEAE)",
            "400": "var(--neutral-400, #939393)",
            "500": "var(--neutral-500, #777777)",
            "600": "var(--neutral-600, #595959)",
            "700": "var(--neutral-700, #393939)",
            "800": "var(--neutral-800, #2A2A2A)",
            "900": "var(--neutral-900, #191919)",
            "950": "var(--neutral-950, #000000)"
          },
          "primary": {
            "0": "var(--primary-0, #FFFFFF)",
            "50": "var(--primary-50, #E6F2FD)",
            "100": "var(--primary-100, #B8D9F9)",
            "200": "var(--primary-200, #8ABEF3)",
            "300": "var(--primary-300, #5CA2E9)",
            "400": "var(--primary-400, #2E86DE)",
            "500": "var(--primary-500, #0067D1)",
            "600": "var(--primary-600, #004EA8)",
            "700": "var(--primary-700, #003D83)",
            "800": "var(--primary-800, #002E6A)",
            "900": "var(--primary-900, #00214B)",
            "950": "var(--primary-950, #000000)"
          },
          "success": {
            "0": "var(--success-0, #FFFFFF)",
            "50": "var(--success-50, #E7FBF2)",
            "100": "var(--success-100, #BCF2DB)",
            "200": "var(--success-200, #8FE5C2)",
            "300": "var(--success-300, #63D5A8)",
            "400": "var(--success-400, #36C18D)",
            "500": "var(--success-500, #09AA71)",
            "600": "var(--success-600, #058358)",
            "700": "var(--success-700, #036142)",
            "800": "var(--success-800, #02422E)",
            "900": "var(--success-900, #00291D)",
            "950": "var(--success-950, #000000)"
          },
          "warning": {
            "0": "var(--warning-0, #FFFFFF)",
            "50": "var(--warning-50, #FEFCE0)",
            "100": "var(--warning-100, #FEF8B8)",
            "200": "var(--warning-200, #FEF08A)",
            "300": "var(--warning-300, #FDE55C)",
            "400": "var(--warning-400, #FCD72E)",
            "500": "var(--warning-500, #FCC800)",
            "600": "var(--warning-600, #D19F00)",
            "700": "var(--warning-700, #9E7400)",
            "800": "var(--warning-800, #614500)",
            "900": "var(--warning-900, #2E1F00)",
            "950": "var(--warning-950, #000000)"
          },
          "alert": {
            "0": "var(--alert-0, #FFFFFF)",
            "50": "var(--alert-50, #FEF5E8)",
            "100": "var(--alert-100, #FDE2BD)",
            "200": "var(--alert-200, #FCCE92)",
            "300": "var(--alert-300, #F9B766)",
            "400": "var(--alert-400, #F69E39)",
            "500": "var(--alert-500, #F4840C)",
            "600": "var(--alert-600, #C76207)",
            "700": "var(--alert-700, #954304)",
            "800": "var(--alert-800, #642802)",
            "900": "var(--alert-900, #3D1601)",
            "950": "var(--alert-950, #000000)"
          },
          "error": {
            "0": "var(--error-0, #FFFFFF)",
            "50": "var(--error-50, #FEE7E8)",
            "100": "var(--error-100, #FABDC1)",
            "200": "var(--error-200, #F59297)",
            "300": "var(--error-300, #EE696F)",
            "400": "var(--error-400, #E7434A)",
            "500": "var(--error-500, #E02128)",
            "600": "var(--error-600, #C7000B)",
            "700": "var(--error-700, #850F12)",
            "800": "var(--error-800, #59080A)",
            "900": "var(--error-900, #350305)",
            "950": "var(--error-950, #000000)"
          },
          "brand": {
            "5": "var(--brand-5, #E6F2FD)",
            "10": "var(--brand-10, #B8D9F9)",
            "20": "var(--brand-20, #8ABEF3)",
            "30": "var(--brand-30, #5CA2E9)",
            "40": "var(--brand-40, #2E86DE)",
            "50": "var(--brand-50, #0067D1)",
            "60": "var(--brand-60, #004EA8)",
            "70": "var(--brand-70, #003D83)",
            "80": "var(--brand-80, #002E6A)",
            "90": "var(--brand-90, #00214B)"
          },
          "gray": {
            "0": "var(--gray-0, #FFFFFF)",
            "5": "var(--gray-5, #F3F3F3)",
            "10": "var(--gray-10, #DFDFDF)",
            "20": "var(--gray-20, #C9C9C9)",
            "30": "var(--gray-30, #AEAEAE)",
            "40": "var(--gray-40, #939393)",
            "50": "var(--gray-50, #777777)",
            "60": "var(--gray-60, #595959)",
            "70": "var(--gray-70, #393939)",
            "80": "var(--gray-80, #2A2A2A)",
            "90": "var(--gray-90, #191919)",
            "100": "var(--gray-100, #000000)"
          },
          "red": {
            "5": "var(--red-5, #FEE7E8)",
            "10": "var(--red-10, #FABDC1)",
            "20": "var(--red-20, #F59297)",
            "30": "var(--red-30, #EE696F)",
            "40": "var(--red-40, #E7434A)",
            "50": "var(--red-50, #E02128)",
            "60": "var(--red-60, #C7000B)",
            "70": "var(--red-70, #850F12)",
            "80": "var(--red-80, #59080A)",
            "90": "var(--red-90, #350305)"
          },
          "rose": {
            "5": "var(--rose-5, #FEE5F2)",
            "10": "var(--rose-10, #FCC3E0)",
            "20": "var(--rose-20, #F99AC7)",
            "30": "var(--rose-30, #F470AB)",
            "40": "var(--rose-40, #ED448A)",
            "50": "var(--rose-50, #E61866)",
            "60": "var(--rose-60, #C40054)",
            "70": "var(--rose-70, #811439)",
            "80": "var(--rose-80, #540D24)",
            "90": "var(--rose-90, #330614)"
          },
          "orange": {
            "5": "var(--orange-5, #FEF5E8)",
            "10": "var(--orange-10, #FDE2BD)",
            "20": "var(--orange-20, #FCCE92)",
            "30": "var(--orange-30, #F9B766)",
            "40": "var(--orange-40, #F69E39)",
            "50": "var(--orange-50, #F4840C)",
            "60": "var(--orange-60, #C76207)",
            "70": "var(--orange-70, #954304)",
            "80": "var(--orange-80, #642802)",
            "90": "var(--orange-90, #3D1601)"
          },
          "yellow": {
            "5": "var(--yellow-5, #FEFCE0)",
            "10": "var(--yellow-10, #FEF8B8)",
            "20": "var(--yellow-20, #FEF08A)",
            "30": "var(--yellow-30, #FDE55C)",
            "40": "var(--yellow-40, #FCD72E)",
            "50": "var(--yellow-50, #FCC800)",
            "60": "var(--yellow-60, #D19F00)",
            "70": "var(--yellow-70, #9E7400)",
            "80": "var(--yellow-80, #614500)",
            "90": "var(--yellow-90, #2E1F00)"
          },
          "green": {
            "5": "var(--green-5, #F2FBE9)",
            "10": "var(--green-10, #DFF4CC)",
            "20": "var(--green-20, #C6E9A8)",
            "30": "var(--green-30, #A8DB81)",
            "40": "var(--green-40, #87C859)",
            "50": "var(--green-50, #62B42E)",
            "60": "var(--green-60, #488E20)",
            "70": "var(--green-70, #316614)",
            "80": "var(--green-80, #1B3E0A)",
            "90": "var(--green-90, #0C2004)"
          },
          "mint": {
            "5": "var(--mint-5, #E7FBF2)",
            "10": "var(--mint-10, #BCF2DB)",
            "20": "var(--mint-20, #8FE5C2)",
            "30": "var(--mint-30, #63D5A8)",
            "40": "var(--mint-40, #36C18D)",
            "50": "var(--mint-50, #09AA71)",
            "60": "var(--mint-60, #058358)",
            "70": "var(--mint-70, #036142)",
            "80": "var(--mint-80, #02422E)",
            "90": "var(--mint-90, #00291D)"
          },
          "cyan": {
            "5": "var(--cyan-5, #E8FCFD)",
            "10": "var(--cyan-10, #C9F6F9)",
            "20": "var(--cyan-20, #A4ECF1)",
            "30": "var(--cyan-30, #7DDFE7)",
            "40": "var(--cyan-40, #55CCD9)",
            "50": "var(--cyan-50, #2CB8C9)",
            "60": "var(--cyan-60, #1C94A4)",
            "70": "var(--cyan-70, #127180)",
            "80": "var(--cyan-80, #094C57)",
            "90": "var(--cyan-90, #04282F)"
          },
          "blue": {
            "5": "var(--blue-5, #EEF3FE)",
            "10": "var(--blue-10, #D0D8FD)",
            "20": "var(--blue-20, #B0BFFD)",
            "30": "var(--blue-30, #8CA3FA)",
            "40": "var(--blue-40, #668CF7)",
            "50": "var(--blue-50, #2070F3)",
            "60": "var(--blue-60, #1F55B5)",
            "70": "var(--blue-70, #1B3F86)",
            "80": "var(--blue-80, #112857)",
            "90": "var(--blue-90, #081635)"
          },
          "indigo": {
            "5": "var(--indigo-5, #EEEEFE)",
            "10": "var(--indigo-10, #D5D3FD)",
            "20": "var(--indigo-20, #BFB9FA)",
            "30": "var(--indigo-30, #A89FF9)",
            "40": "var(--indigo-40, #8E81F4)",
            "50": "var(--indigo-50, #715AFB)",
            "60": "var(--indigo-60, #5531EB)",
            "70": "var(--indigo-70, #3F21B5)",
            "80": "var(--indigo-80, #281675)",
            "90": "var(--indigo-90, #160B48)"
          },
          "purple": {
            "5": "var(--purple-5, #F7EDFE)",
            "10": "var(--purple-10, #E8CFFE)",
            "20": "var(--purple-20, #D9B1FD)",
            "30": "var(--purple-30, #CB8EFB)",
            "40": "var(--purple-40, #BF68FA)",
            "50": "var(--purple-50, #B62BF7)",
            "60": "var(--purple-60, #8A21BC)",
            "70": "var(--purple-70, #651B8B)",
            "80": "var(--purple-80, #41125A)",
            "90": "var(--purple-90, #260937)"
          },
          "pink": {
            "5": "var(--pink-5, #FDE6FC)",
            "10": "var(--pink-10, #F9C5F6)",
            "20": "var(--pink-20, #F39DEC)",
            "30": "var(--pink-30, #EB74DF)",
            "40": "var(--pink-40, #E049CE)",
            "50": "var(--pink-50, #D41DBC)",
            "60": "var(--pink-60, #9F1C8D)",
            "70": "var(--pink-70, #751868)",
            "80": "var(--pink-80, #4C0F43)",
            "90": "var(--pink-90, #2E0728)"
          }
        },

        /* ==========================================================================
           HUI 语义色 (Component Tokens) — from hui-base.css :root ~ line 180
           Usage: text-hui-text-primary, bg-hui-bg-1, border-hui-border, text-hui-chart-1
           ========================================================================== */
        "hui": {
          "brand": "var(--color-brand)",
          "brand-hover": "var(--color-brand-hover)",
          "brand-focus": "var(--color-brand-focus)",
          "brand-active": "var(--color-brand-active)",
          "brand-disabled": "var(--color-brand-disabled)",

          "text-primary": "var(--color-text-primary)",
          "text-secondary": "var(--color-text-secondary)",
          "text-placeholder": "var(--color-text-placeholder)",
          "text-disabled": "var(--color-text-disabled)",
          "text-inverse": "var(--color-text-inverse)",
          "text-inverse-disabled": "var(--color-text-inverse-disabled)",
          "text-on": "var(--color-text-on)",
          "link": "var(--color-link)",
          "link-hover": "var(--color-link-hover)",
          "link-active": "var(--color-link-active)",
          "link-visited": "var(--color-link-visited)",
          "link-disabled": "var(--color-link-disabled)",

          "bg-1": "var(--color-bg-1)",
          "bg-2": "var(--color-bg-2)",
          "bg-3": "var(--color-bg-3)",
          "bg-4": "var(--color-bg-4)",
          "bg-5": "var(--color-bg-5)",
          "bg-6": "var(--color-bg-6)",
          "bg-mask": "var(--color-bg-mask)",

          "fill-disabled": "var(--color-fill-disabled)",
          "hover": "var(--color-hover)",
          "fill-disabled-subtle": "var(--color-fill-disabled-subtle)",
          "fill": "var(--color-fill)",
          "select": "var(--color-select)",
          "fill-subtle": "var(--color-fill-subtle)",

          "icon-primary": "var(--color-icon-primary)",
          "icon-secondary": "var(--color-icon-secondary)",
          "icon-tertiary": "var(--color-icon-tertiary)",
          "icon-placeholder": "var(--color-icon-placeholder)",
          "icon-disabled": "var(--color-icon-disabled)",
          "icon-inverse": "var(--color-icon-inverse)",
          "icon-hover": "var(--color-icon-hover)",
          "icon-focus": "var(--color-icon-focus)",
          "icon-active": "var(--color-icon-active)",

          "border": "var(--color-border)",
          "border-hover": "var(--color-border-hover)",
          "border-focus": "var(--color-border-focus)",
          "border-active": "var(--color-border-active)",
          "border-disabled": "var(--color-border-disabled)",
          "border-separator": "var(--color-border-separator)",
          "border-separator-subtle": "var(--color-border-separator-sbutle)",

          "error": "var(--color-error)",
          "error-hover": "var(--color-error-hover)",
          "error-active": "var(--color-error-active)",
          "error-disabled": "var(--color-error-disabled)",
          "error-subtle": "var(--color-error-subtle)",
          "error-subtler": "var(--color-error-subtler)",

          "alert": "var(--color-alert)",
          "alert-hover": "var(--color-alert-hover)",
          "alert-active": "var(--color-alert-active)",
          "alert-disabled": "var(--color-alert-disabled)",
          "alert-subtle": "var(--color-alert-subtle)",
          "alert-subtler": "var(--color-alert-subtler)",

          "warning": "var(--color-warning)",
          "warning-hover": "var(--color-warning-hover)",
          "warning-active": "var(--color-warning-active)",
          "warning-disabled": "var(--color-warning-disabled)",
          "warning-bold": "var(--color-warning-bold)",
          "warning-subtle": "var(--color-warning-subtle)",
          "warning-subtler": "var(--color-warning-subtler)",

          "success": "var(--color-success)",
          "success-hover": "var(--color-success-hover)",
          "success-active": "var(--color-success-active)",
          "success-disabled": "var(--color-success-disabled)",
          "success-subtle": "var(--color-success-subtle)",
          "success-subtler": "var(--color-success-subtler)",

          "info-primary": "var(--color-info-primary)",
          "info-primary-subtle": "var(--color-info-primary-subtle)",
          "info-primary-subtler": "var(--color-info-primary-subtler)",
          "info-secondary": "var(--color-info-secondary)",
          "info-secondary-hover": "var(--color-info-secondary-hover)",
          "info-secondary-active": "var(--color-info-secondary-active)",
          "info-secondary-disabled": "var(--color-info-secondary-disabled)",
          "info-secondary-subtle": "var(--color-info-secondary-subtle)",

          "none": "var(--color-none)",
          "none-hover": "var(--color-none-hover)",
          "none-active": "var(--color-none-active)",
          "none-disabled": "var(--color-none-disabled)",
          "none-subtle": "var(--color-none-subtle)",

          "chart-1": "var(--color-chart-1)",
          "chart-2": "var(--color-chart-2)",
          "chart-3": "var(--color-chart-3)",
          "chart-4": "var(--color-chart-4)",
          "chart-6": "var(--color-chart-6)",
          "chart-7": "var(--color-chart-7)",
          "chart-8": "var(--color-chart-8)",
          "chart-9": "var(--color-chart-9)",
          "chart-10": "var(--color-chart-10)",
          "chart-11": "var(--color-chart-11)",
          "chart-12": "var(--color-chart-12)",
          "chart-13": "var(--color-chart-13)",
          "chart-14": "var(--color-chart-14)",
          "chart-15": "var(--color-chart-15)",
          "chart-16": "var(--color-chart-16)",
          "chart-17": "var(--color-chart-17)",
          "chart-18": "var(--color-chart-18)",
          "chart-19": "var(--color-chart-19)",
          "chart-20": "var(--color-chart-20)",
          "chart-21": "var(--color-chart-21)",
          "chart-22": "var(--color-chart-22)",
          "chart-23": "var(--color-chart-23)",
          "chart-24": "var(--color-chart-24)",
          "chart-25": "var(--color-chart-25)",

          "scrollbar": "var(--color-scrollbar)",
          "scrollbar-hover": "var(--color-scrollbar-hover)",
          "card-gray-disabled": "var(--color-card-gray-disabled)",
          "card-white-disabled": "var(--color-card-white-disabled)",
          "sidenav-bg": "var(--color-sidenav-bg)",
          "table-header": "var(--color-table-header)",
          "table-zebra": "var(--color-table-zebra)",
          "radiogp-bg": "var(--color-radiogp-bg)",
          "radiogp-text": "var(--color-radiogp-text)",
          "message-bg-info": "var(--color-message-bg-info)",
          "message-bg-success": "var(--color-message-bg-success)",
          "message-bg-warning": "var(--color-message-bg-warning)",
          "message-bg-alert": "var(--color-message-bg-alert)",
          "message-bg-error": "var(--color-message-bg-error)",

          "tag-text-purple": "var(--color-tag-text-purple)",
          "tag-bg-purple": "var(--color-tag-bg-purple)",
          "tag-text-cyan": "var(--color-tag-text-cyan)",
          "tag-bg-cyan": "var(--color-tag-bg-cyan)",
          "tag-text-rose": "var(--color-tag-text-rose)",
          "tag-bg-rose": "var(--color-tag-bg-rose)",
          "tag-text-green": "var(--color-tag-text-green)",
          "tag-bg-green": "var(--color-tag-bg-green)",
          "tag-text-pink": "var(--color-tag-text-pink)",
          "tag-bg-pink": "var(--color-tag-bg-pink)",
          "tag-text-indigo": "var(--color-tag-text-indigo)",
          "tag-bg-indigo": "var(--color-tag-bg-indigo)",
          "tag-text-none": "var(--color-tag-text-none)",
          "tag-bg-none": "var(--color-tag-bg-none)",
          "tag-text-error": "var(--color-tag-text-error)",
          "tag-bg-error": "var(--color-tag-bg-error)",
          "tag-text-alert": "var(--color-tag-text-alert)",
          "tag-bg-alert": "var(--color-tag-bg-alert)",
          "tag-text-warning": "var(--color-tag-text-warning)",
          "tag-bg-warning": "var(--color-tag-bg-warning)",
          "tag-text-success": "var(--color-tag-text-success)",
          "tag-bg-success": "var(--color-tag-bg-success)",
          "tag-text-info": "var(--color-tag-text-info)",
          "tag-bg-info": "var(--color-tag-bg-info)"
        }
      },
      "spacing": {
        'inline': '0.5rem',
        'stack': '0.75rem',
        'gutter': '1rem', 
        'inset': '1.5rem',
        'section': '1rem', 
        'page': '2rem'    
      },
      "boxShadow": {
        'sm': 'var(--shadow-sm, 1px 1px 6px 0 rgba(0, 0, 0, 0.08))',
        'md': 'var(--shadow-md, 0 4px 12px 0px rgba(0, 0, 0, 0.16))',
        'lg': 'var(--shadow-lg, 0 8px 24px 0px rgba(0, 0, 0, 0.16))',
        'xl': 'var(--shadow-xl, 0 16px 48px 0px rgba(0, 0, 0, 0.16))',
        'card': 'var(--shadow-sm, 1px 1px 6px 0 rgba(0, 0, 0, 0.08))',
        'popover': 'var(--shadow-lg, 0 8px 24px 0px rgba(0, 0, 0, 0.16))',
        'modal': 'var(--shadow-xl, 0 16px 48px 0px rgba(0, 0, 0, 0.16))'
      },
      "borderColor": {
        'base': 'var(--border, #C9C9C9)',
        'divider': 'var(--divider, #F3F3F3)',
        'selected': 'var(--primary-500, #0067D1)',
        'error': 'var(--error-500, #E02128)',
      },
      "borderRadius": {
        'none': '0px',
        'sm': '2px', 
        'md': '4px',
        'lg': '6px',
        'xl': '8px',
        'full': '9999px',
        'badge': '4px',
        'action': '4px',
        'container': '8px',
        'overlay': '8px'
      },
      "outlineColor": {
        'brand': 'var(--primary-500, #0067D1)',
        'error': 'var(--error-500, #E02128)'
      },
      "outlineWidth": {
        'focus': '1px',
      },
      "outlineOffset": {
        'gap': '2px',
      },
      "fontSize": {
        "xs": ["10px", { "lineHeight": "1.8" }],
        "sm": ["12px", { "lineHeight": "1.6" }],
        "md": ["14px", { "lineHeight": "1.5" }],
        "lg": ["16px", { "lineHeight": "1.5" }],
        "xl": ["18px", { "lineHeight": "1.5" }],
        "2xl": ["20px", { "lineHeight": "1.4" }],
        "3xl": ["24px", { "lineHeight": "1.4" }],
        "4xl": ["28px", { "lineHeight": "1.4" }],
        "5xl": ["36px", { "lineHeight": "1.4" }],
        "6xl": ["48px", { "lineHeight": "1.3" }],
        "7xl": ["60px", { "lineHeight": "1.3" }],
        "8xl": ["72px", { "lineHeight": "1.2" }],
        "9xl": ["96px", { "lineHeight": "1.2" }]
      }
    }
  },
} satisfies Config